# Generated by Django 5.0.2 on 2024-03-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0004_remove_profile_status_alter_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
