services:
  portfolio_django:
    container_name: portfolio-server
    build:
      context: .
    image: django-portfolio:dev
    ports:
      - "8000:8000"
    volumes:
      - ./portfolio:/portfolio
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - portfolio_db
 #Mudei a versao do banco de dados vai dar problema tem que ser ajeitado
  portfolio_db:
    container_name: portfolio-db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

volumes:
  database:
