services:
  portfolio_django:
    container_name: portifolio-server
    build:
      context: .
    image: django-portifolio:dev
    ports:
      - 8000:8000
    volumes:
      - ./portifolio:/portifolio
      - ./portifolio/static:/portifolio/static/
      - ./portifolio/apps/home/static/home:/portifolio/static/home
      - ./portifolio/apps/picpay/static/picpay:/portifolio/static/picpay
      - ./portifolio/media:/portifolio/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - portfolio_db

  portfolio_db:
    container_name: portfolio-db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
