services:
  portifolio:
    container_name: portifolio-server
    build:
      context: .
    ports:
      - 8000:8000 
    volumes:
      - ./portifolio:/portifolio
      - ./portifolio/static:/portifolio/static/
      - ./portifolio/home/static/home:/portifolio/static/home
      - ./portifolio/media:/portifolio/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - portiDB

  portiDB:
    container_name: portiDB
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  portiNginx:  
    container_name: portiNginx
    image: nginx:1.25.1
    ports:
      - 80:80 
      - 443:443  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./portifolio/static:/portifolio/static/
      - ./portifolio/home/static/home:/portifolio/static/home
      - ./portifolio/webchat/static/webchat:/portifolio/static/webchat
      - ./portifolio/media:/portifolio/media/
      - ./certbot/etc/letsencrypt:/etc/letsencrypt 
      - ./certbot-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    depends_on:
      - portifolio

  