services:
  portfolio_django:
    container_name: portifolio-server
    build:
      context: .
    image: django-portifolio:dev  
    ports:
      - 8000:8000 
    volumes:
      - ./portifolio:/portifolio
      - ./portifolio/static:/portifolio/static/
      - ./portifolio/apps/home/static/home:/portifolio/static/home
      - ./portifolio/apps/picpay/static/picpay:/portifolio/static/picpay
      - ./portifolio/media:/portifolio/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - portfolio_db 

  portfolio_db:
    container_name: portfolio-db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  portfolio_nginx:  
    container_name: portfolio-nginx
    image: nginx:1.25.1
    ports:
      - 80:80 
      - 443:443  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./portifolio/static:/portifolio/static/
      - ./portifolio/apps/home/static/home:/portifolio/static/home
      - ./portifolio/apps/webchat/static/webchat:/portifolio/static/webchat
      - ./portifolio/apps/picpay/static/picpay:/portifolio/static/picpay
      - ./portifolio/media:/portifolio/media/
      - ./certbot-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    depends_on:
      - portfolio_django

  