services:
  django:
    container_name: django-server
    build:
      context: .
    ports:
      - 8000:8000 
    volumes:
      - ./django:/django
      - ./django/static:/django/static/
      - ./django/media:/django/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - portiDB

  portiDB:
    container_name: portiDB
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env

  portiNginx:  
    container_name: portiNginx
    image: nginx:1.25.1
    ports:
      - 80:80 
      - 443:443  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./django/static:/django/static/
      - ./certbot/etc/letsencrypt:/etc/letsencrypt 
      - ./certbot-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    depends_on:
      - django

  certbot:
    build: ./certbot
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
