# Generated by Django 5.0.2 on 2024-02-23 19:15

import webchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_alter_profile_friends_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='webchat/empty_picture.jpg', null=True, upload_to=webchat.models.get_profile_picture_path),
        ),
    ]
