# Generated by Django 6.0.4 on 2026-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_pt", models.TextField(blank=True)),
                ("content_en", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Me",
                "verbose_name_plural": "About Me",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="projects/")),
                ("title_pt", models.CharField(max_length=120)),
                ("title_en", models.CharField(max_length=120)),
                ("short_description_pt", models.TextField()),
                ("short_description_en", models.TextField()),
                ("project_url", models.URLField()),
                ("read_more_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_pt", models.FileField(blank=True, upload_to="resume/")),
                ("file_en", models.FileField(blank=True, upload_to="resume/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resume",
            },
        ),
    ]
