# Generated by Django 6.0.4 on 2026-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
