# Generated by Django 5.1.1 on 2025-08-29 17:01

import apps.webchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/webchat/images/icons/empty_picture.jpg', upload_to=apps.webchat.models.get_profile_picture_path),
        ),
    ]
