# Generated by Django 5.0.7 on 2024-07-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='account_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
