# Generated by Django 5.0.7 on 2024-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0002_rename_type_profile_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4),
        ),
    ]
