# Generated by Django 5.0.7 on 2024-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0003_alter_profile_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='complete_name',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
