# Generated by Django 5.1.1 on 2025-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picpayaccount',
            name='complete_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picpayaccount',
            name='document',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
